name: Build and Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          ~/.local/share/NuGet
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.vbproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: Setup .NET
      run: |
        dotnet tool install --global MSBuild.Extension.Pack
        dotnet msbuild /restore pbtgui.sln

    - name: Build
      run: |
        dotnet msbuild /t:build /p:Configuration=Release /p:Platform="Any CPU" pbtgui.sln

    - name: Create ClickOnce Directory
      run: |
        if (!(Test-Path bin/ClickOnce)) {
          New-Item -ItemType Directory -Path bin/ClickOnce
        }

    - name: Publish ClickOnce Application
      run: |
        dotnet msbuild /t:publish /p:Configuration=Release /p:Platform="Any CPU" pbtgui.sln
