name: Publish ClickOnce Application

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore pbtgui.sln

    - name: Build ClickOnce Application
      run: msbuild /t:publish /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:PublishDir="bin\ClickOnce" pbtgui.sln

    - name: Copy Executable to Publish Directory
      run: |
        cp bin/Release/*.exe bin/ClickOnce

  manual-publish:
    runs-on: windows-2022
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Publish ClickOnce Application
      run: msbuild /t:publish /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:PublishDir="bin\ClickOnce" pbtgui.sln

    - name: Copy Executable to Publish Directory
      run: |
        mkdir -p bin/ClickOnce
        cp bin/Release/*.exe bin/ClickOnce
