name: Build
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'     
        required: true
        type: string
      info:
        description: 'Description of this Release'
        required: true
        type: string
    tags:
    - 'v*'
jobs:
  build:
    name: Create build
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet packages
      run: nuget restore pbtgui.sln
    - name: Build executable
      run: msbuild /t:build /p:Configuration=Release pbtgui.sln
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: pbtgui
        path: bin/Release/pbtgui.exe
        if-no-files-found: error
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: pbtgui
          path: bin/Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version_number }}
          release_name: V ${{ github.event.inputs.version_number }}
          draft: false
          prerelease: false
          body: |
            ${{ github.event.inputs.info }}
        
        - name: Upload executable
          uses: actions/upload-release-asset@v1
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: bin/Release/pbtgui.exe
            asset_name: pbtgui
            asset_content_type: application/gzip