name: Build
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'     
        required: true
        type: string
      info:
        description: 'Description of this Release'
        required: true
        type: string
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet packages
      run: nuget restore pbtgui.sln
    - name: Build executable
      run: msbuild /t:build /p:Configuration=Release pbtgui.sln
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: pbtgui
        path: bin/Release/pbtgui-${{ github.event.inputs.version_number }}.exe
        if-no-files-found: error
  release:
    name: Create Release
    runs-on: windows-2022
    needs: build
    - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: bin/Release/pbtgui-${{ github.event.inputs.version_number }}.exe
          path: bin/Release
    - name: Show Artifacts
      run: ls -R
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.version_number }}
        name: Version ${{ github.event.inputs.version_number }}
        draft: true
        prerelease: false
        artifacts: "*.exe"
        body: |
          ${{ github.event.inputs.info }}