name: Build Windows Form App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      CI: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: dotnet restore pbtgui.sln

    - name: Build
      run: dotnet build pbtgui.sln --configuration Release

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: bin/Release/
